// ============================================================
// قاعدة بيانات الأدوية الشاملة — يمكن تعديلها من لوحة الأدمن
// ============================================================
const DRUG_DATABASE_DEFAULT = [

// ═══════════════════════════════════════════
// أدوية القلب والأوعية الدموية
// ═══════════════════════════════════════════
{id:'d001',name:'Aspirin (أسبرين)',category:'القلب والأوعية',dose:'75-325mg',freq:'مرة يومياً',timing:'08:00 مع الطعام',food:'مع الطعام أو بعده',route:'فموي',sideEffects:'نزيف هضمي، قرحة، طنين (بجرعات عالية)',contraindications:'قرحة نشطة، حساسية، أطفال <16 سنة',renalAdj:'احتياط مع GFR<10',interactions:'Warfarin, NSAIDs, Heparin',mechanism:'مثبط COX لا ارتدادي',halfLife:'15-20 دقيقة (حمض صالسيليك 2-3 ساعات)',blackBox:'',notes:'للوقاية القلبية: 75-100mg يومياً. مضغ الأولى للذبحة الحادة.',optimalTime:'08:00',category2:'مضاد تخثر'},

{id:'d002',name:'Atorvastatin (أتورفاستاتين)',category:'القلب والأوعية',dose:'10-80mg',freq:'مرة يومياً',timing:'في أي وقت — 20:00 مفضل',food:'بغض النظر عن الطعام',route:'فموي',sideEffects:'ألم عضلي، رفع إنزيمات الكبد، صداع',contraindications:'حمل، إرضاع، أمراض كبد نشطة',renalAdj:'لا تعديل',interactions:'Amiodarone, Erythromycin, Antifungals, Grapefruit',mechanism:'مثبط HMG-CoA Reductase',halfLife:'14 ساعة',blackBox:'',notes:'مراقبة CPK وكبد كل 6-12 شهراً. تجنب عصير الجريب فروت.',optimalTime:'20:00',category2:'خافض دهون'},

{id:'d003',name:'Simvastatin (سيمفاستاتين)',category:'القلب والأوعية',dose:'10-40mg',freq:'مرة يومياً',timing:'20:00',food:'بغض النظر عن الطعام',route:'فموي',sideEffects:'ألم عضلي، رابدوميوليسيس (نادر)، رفع كبد',contraindications:'حمل، أمراض كبد، مع Amiodarone >20mg',renalAdj:'احتياط مع GFR<30',interactions:'Amiodarone (max 20mg), Amlodipine (max 20mg), Diltiazem',mechanism:'مثبط HMG-CoA Reductase',halfLife:'2 ساعة',blackBox:'خطر اعتلال عضلي مع بعض التركيبات',notes:'الحد الأقصى 20mg مع Amiodarone. تجنب الجريب فروت.',optimalTime:'20:00',category2:'خافض دهون'},

{id:'d004',name:'Metoprolol (ميتوبرولول)',category:'القلب والأوعية',dose:'25-200mg',freq:'مرة-مرتين يومياً',timing:'08:00 (أو مقسمة)',food:'مع الطعام',route:'فموي',sideEffects:'بطء قلب، برودة أطراف، تعب، كوابيس، ضيق تنفس',contraindications:'بطء قلب شديد، انسداد AV درجة 2-3، صدمة قلبية',renalAdj:'لا تعديل',interactions:'Verapamil, Diltiazem, Clonidine',mechanism:'حاصر بيتا 1 انتقائي',halfLife:'3-7 ساعات',blackBox:'لا توقف فجأة — تدرج في الإيقاف',notes:'XL/Succinate: مرة يومياً. Tartrate: مرتين. لا توقف فجأة.',optimalTime:'08:00',category2:'حاصر بيتا'},

{id:'d005',name:'Bisoprolol (بيسوبرولول)',category:'القلب والأوعية',dose:'1.25-10mg',freq:'مرة يومياً',timing:'08:00',food:'مع أو بدون طعام',route:'فموي',sideEffects:'بطء قلب، تعب، دوخة، برودة أطراف',contraindications:'انسداد AV، قصور قلب حاد، بطء قلب شديد',renalAdj:'احتياط مع GFR<20',interactions:'Verapamil, Diltiazem, Antiarrhythmics',mechanism:'حاصر بيتا 1 انتقائي عالي',halfLife:'10-12 ساعة',blackBox:'لا توقف فجأة',notes:'المفضل في قصور القلب. ابدأ بجرعة منخفضة وزد تدريجياً.',optimalTime:'08:00',category2:'حاصر بيتا'},

{id:'d006',name:'Amlodipine (أملوديبين)',category:'القلب والأوعية',dose:'2.5-10mg',freq:'مرة يومياً',timing:'في أي وقت',food:'بغض النظر عن الطعام',route:'فموي',sideEffects:'وذمة قدمين، احمرار وجه، صداع، خفقان',contraindications:'صدمة قلبية، تضيق أبهر شديد',renalAdj:'لا تعديل',interactions:'Simvastatin (max 20mg), Cyclosporine',mechanism:'حاصر قنوات كالسيوم ديهيدروبيريدين',halfLife:'30-50 ساعة',blackBox:'',notes:'وذمة الساقين شائعة — أخبر المريض. تأثير تراكمي يظهر بعد أسابيع.',optimalTime:'أي وقت',category2:'حاصر كالسيوم'},

{id:'d007',name:'Lisinopril (ليزينوبريل)',category:'القلب والأوعية',dose:'2.5-40mg',freq:'مرة يومياً',timing:'08:00',food:'بغض النظر عن الطعام',route:'فموي',sideEffects:'سعال جاف، دوخة، فرط بوتاسيوم، وذمة وعائية (نادر)',contraindications:'حمل، وذمة وعائية سابقة، تضيق الشريان الكلوي الثنائي',renalAdj:'تخفيف: GFR 10-30: 5mg. <10: 2.5mg',interactions:'Potassium supplements, Spironolactone, NSAIDs, Aliskiren',mechanism:'مثبط ACE',halfLife:'12 ساعة',blackBox:'ممنوع في الحمل — تشوهات جنينية',notes:'السعال الجاف شائع 10-15%، بديله ARBs. راقب الكرياتينين والبوتاسيوم.',optimalTime:'08:00',category2:'مثبط ACE'},

{id:'d008',name:'Ramipril (راميبريل)',category:'القلب والأوعية',dose:'1.25-10mg',freq:'مرة-مرتين يومياً',timing:'08:00',food:'بغض النظر عن الطعام',route:'فموي',sideEffects:'سعال، دوخة، فرط بوتاسيوم',contraindications:'حمل، وذمة وعائية، تضيق ثنائي للشريان الكلوي',renalAdj:'GFR<30: ابدأ 1.25mg',interactions:'Potassium, NSAIDs, Lithium',mechanism:'مثبط ACE (prodrug)',halfLife:'13-17 ساعة',blackBox:'ممنوع في الحمل',notes:'فائدة إضافية في الكلى السكرية.',optimalTime:'08:00',category2:'مثبط ACE'},

{id:'d009',name:'Losartan (لوسارتان)',category:'القلب والأوعية',dose:'25-100mg',freq:'مرة يومياً',timing:'أي وقت',food:'بغض النظر عن الطعام',route:'فموي',sideEffects:'دوخة، فرط بوتاسيوم، نادراً: وذمة وعائية',contraindications:'حمل، تضيق ثنائي الشريان الكلوي',renalAdj:'لا تعديل كبير',interactions:'Potassium, NSAIDs, Aliskiren, ACE Inhibitors',mechanism:'حاصر مستقبل أنجيوتنسين II (ARB)',halfLife:'2 ساعة (نشط 6-9 ساعات)',blackBox:'ممنوع في الحمل',notes:'بديل ممتاز لمثبطات ACE عند السعال. حماية كلوية في السكري.',optimalTime:'أي وقت',category2:'ARB'},

{id:'d010',name:'Valsartan (فالسارتان)',category:'القلب والأوعية',dose:'40-320mg',freq:'مرة-مرتين يومياً',timing:'أي وقت',food:'بغض النظر عن الطعام',route:'فموي',sideEffects:'دوخة، فرط بوتاسيوم',contraindications:'حمل',renalAdj:'GFR>10: لا تعديل',interactions:'Potassium, NSAIDs, Lithium',mechanism:'حاصر ARB',halfLife:'6 ساعات',blackBox:'ممنوع في الحمل',notes:'مفيد في قصور القلب. راقب ضغط الدم الوضعي.',optimalTime:'أي وقت',category2:'ARB'},

{id:'d011',name:'Furosemide (فيوروسيمايد)',category:'القلب والأوعية',dose:'20-80mg',freq:'مرة-مرتين يومياً',timing:'08:00 (لتفادي التبول الليلي)',food:'بغض النظر عن الطعام',route:'فموي / وريدي',sideEffects:'نقص بوتاسيوم، جفاف، دوخة، نقص صوديوم',contraindications:'انقطاع بول، نقص حجم شديد',renalAdj:'قد تحتاج جرعات أعلى',interactions:'Aminoglycosides (سمية كلى/أذن), Lithium, Digoxin',mechanism:'مدر بول عروة Henle',halfLife:'1-2 ساعة',blackBox:'قد يسبب جفافاً وخللاً شديداً في الشوارد',notes:'راقب البوتاسيوم والصوديوم. أعطِ 08:00 لتجنب الإزعاج الليلي.',optimalTime:'08:00',category2:'مدر بول'},

{id:'d012',name:'Spironolactone (سبيرونولاكتون)',category:'القلب والأوعية',dose:'12.5-50mg',freq:'مرة يومياً',timing:'08:00',food:'مع الطعام',route:'فموي',sideEffects:'فرط بوتاسيوم، تثدي عند الرجال، دورة غير منتظمة',contraindications:'فرط بوتاسيوم، قصور كلوي شديد',renalAdj:'تجنب مع GFR<30 أو بحذر شديد',interactions:'ACE inhibitors, ARBs, NSAIDs, Potassium',mechanism:'مضاد ألدوستيرون',halfLife:'1.4 ساعة (نشط 2-3 أيام)',blackBox:'',notes:'فائدة في قصور القلب والكبد. راقب البوتاسيوم دورياً.',optimalTime:'08:00',category2:'مدر بول'},

{id:'d013',name:'Digoxin (ديجوكسين)',category:'القلب والأوعية',dose:'0.125-0.25mg',freq:'مرة يومياً',timing:'في أي وقت',food:'بغض النظر (تجنب ألياف عالية وقت الجرعة)',route:'فموي',sideEffects:'غثيان، قيء، اضطراب رؤية (أصفر/أخضر)، اضطراب إيقاع',contraindications:'انسداد AV، رجفان بطيني',renalAdj:'تخفيف جذري: GFR<50: 0.125mg. GFR<30: يومياً متناوباً',interactions:'Amiodarone (يضاعف المستوى), Verapamil, Clarithromycin, Antacids',mechanism:'مثبط Na/K-ATPase',halfLife:'36-48 ساعة',blackBox:'نطاق علاجي ضيق — مراقبة مستوى الدواء',notes:'المستوى العلاجي: 0.5-2 ng/mL. مراقبة K⁺ (نقص البوتاسيوم يزيد السمية).',optimalTime:'أي وقت ثابت',category2:'جليكوسيد قلبي'},

{id:'d014',name:'Amiodarone (أميودارون)',category:'القلب والأوعية',dose:'200mg',freq:'مرة يومياً (صيانة)',timing:'مع الطعام',food:'مع الطعام',route:'فموي',sideEffects:'تأثير درقية، تليف رئوي، تغير لون جلد، اضطراب رؤية',contraindications:'بطء قلب، انسداد AV، أمراض درقية',renalAdj:'لا تعديل',interactions:'Warfarin (يضاعف تأثيره), Digoxin, Simvastatin, QT-prolonging drugs',mechanism:'مضاد اضطراب نظم Class III',halfLife:'40-55 يوم',blackBox:'سمية رئوية، كبدية، درقية قد تكون قاتلة',notes:'فحص درقية وكبد وصدر كل 6 شهور. نصف العمر الطويل جداً مهم.',optimalTime:'مع وجبة',category2:'مضاد اضطراب نظم'},

{id:'d015',name:'Warfarin (وارفارين)',category:'القلب والأوعية',dose:'حسب INR',freq:'مرة يومياً',timing:'نفس الوقت يومياً (20:00 مفضل)',food:'ثابت مع الخضروات الورقية',route:'فموي',sideEffects:'نزيف، كدمات، نزيف دماغي',contraindications:'حمل، نزيف نشط، تدخل جراحي',renalAdj:'احتياط',interactions:'Aspirin, NSAIDs, Amiodarone, Antibiotics, Vitamin K foods',mechanism:'مثبط فيتامين K Epoxide Reductase',halfLife:'20-60 ساعة',blackBox:'خطر نزيف قد يكون قاتلاً',notes:'INR المستهدف: 2-3 عادةً. ثبّت كميات الخضار الورقية. مراقبة INR دورية.',optimalTime:'20:00 (وقت ثابت)',category2:'مضاد تخثر'},

{id:'d016',name:'Rivaroxaban (ريفاروكسابان)',category:'القلب والأوعية',dose:'10-20mg',freq:'مرة يومياً',timing:'مع وجبة الغداء أو العشاء',food:'مع الطعام (يزيد الامتصاص)',route:'فموي',sideEffects:'نزيف، أنيميا',contraindications:'نزيف نشط، GFR<15، حمل',renalAdj:'GFR 15-50: 15mg. تجنب <15',interactions:'Antifungals القوية, Rifampicin, P-gp inhibitors',mechanism:'مثبط مباشر Factor Xa',halfLife:'5-9 ساعة',blackBox:'',notes:'لا يحتاج مراقبة روتينية. لا ترياق متاح في كل المراكز (Andexanet alfa).',optimalTime:'مع الوجبة الرئيسية',category2:'مضاد تخثر'},

{id:'d017',name:'Clopidogrel (كلوبيدوجريل)',category:'القلب والأوعية',dose:'75mg',freq:'مرة يومياً',timing:'أي وقت',food:'بغض النظر عن الطعام',route:'فموي',sideEffects:'نزيف، نزيف هضمي، طفح',contraindications:'نزيف نشط',renalAdj:'لا تعديل',interactions:'PPIs (خاصة Omeprazole), Aspirin, Warfarin',mechanism:'مثبط ADP P2Y12',halfLife:'6 ساعات (نشط)',blackBox:'',notes:'تفضيل Pantoprazole على Omeprazole للحد من التداخل. لا توقف قبل الجراحة إلا بتوجيه.',optimalTime:'أي وقت ثابت',category2:'مضاد صفيحات'},

// ═══════════════════════════════════════════
// أدوية السكري
// ═══════════════════════════════════════════
{id:'d018',name:'Metformin (ميتفورمين)',category:'السكري',dose:'500-1000mg',freq:'مرتين-ثلاث مرات يومياً',timing:'مع الوجبات',food:'مع الطعام (يقلل الغثيان)',route:'فموي',sideEffects:'غثيان، إسهال، ألم بطن، نقص B12 طويل الأمد',contraindications:'GFR<30، حماض، قبل الصبغة الوريدية، كبد شديد',renalAdj:'GFR 30-45: تخفيض. <30: ممنوع',interactions:'Iodinated contrast (وقف 48 ساعة), Alcohol',mechanism:'مثبط بيروفات كيناز Mitochondria',halfLife:'4-8 ساعات',blackBox:'خطر الحماض اللبني مع القصور الكلوي',notes:'الخط الأول في DM2. نقص B12 مع الاستخدام الطويل. XR أقل أعراضاً هضمية.',optimalTime:'مع الوجبات',category2:'Biguanide'},

{id:'d019',name:'Glibenclamide (جليبنكلاميد)',category:'السكري',dose:'2.5-15mg',freq:'مرة-مرتين يومياً',timing:'قبل الإفطار (30 دقيقة)',food:'قبل الطعام',route:'فموي',sideEffects:'نقص سكر، زيادة وزن',contraindications:'DM1، قصور كلوي/كبدي شديد، حمل',renalAdj:'تجنب مع GFR<60',interactions:'NSAIDs, Beta-blockers (يخفي أعراض نقص السكر)',mechanism:'سلفونيل يوريا — يحفز البنكرياس',halfLife:'10 ساعة',blackBox:'',notes:'نقص السكر شائع خاصة عند كبار السن. لا يُفضّل في المسنين.',optimalTime:'قبل الإفطار 30 دقيقة',category2:'سلفونيل يوريا'},

{id:'d020',name:'Gliclazide MR (جليكلازيد)',category:'السكري',dose:'30-120mg',freq:'مرة يومياً',timing:'08:00',food:'08:00',route:'فموي',sideEffects:'نقص سكر (أقل من Glibenclamide)، زيادة وزن طفيفة',contraindications:'DM1، كبد شديد، حمل',renalAdj:'حذر مع GFR<30',interactions:'NSAIDs, Fluconazole, Rifampicin',mechanism:'سلفونيل يوريا',halfLife:'10-12 ساعة',blackBox:'',notes:'أكثر أماناً من Glibenclamide في المسنين. MR مرة يومياً.',optimalTime:'08:00',category2:'سلفونيل يوريا'},

{id:'d021',name:'Empagliflozin (إمباجليفلوزين)',category:'السكري',dose:'10-25mg',freq:'مرة يومياً',timing:'08:00',food:'بغض النظر عن الطعام',route:'فموي',sideEffects:'التهابات المسالك/التناسلية، تبول متكرر، نقص حجم',contraindications:'GFR<20، DM1، مثبطات وريدية للقدم السكرية',renalAdj:'لا يعمل فعلياً مع GFR<20',interactions:'Diuretics (زيادة جفاف), Insulin (خطر DKA)',mechanism:'مثبط SGLT-2',halfLife:'12 ساعة',blackBox:'حماض كيتوني سكري حتى مع سكر طبيعي',notes:'فائدة قلبية وكلوية مثبتة. وقف قبل الجراحة 3 أيام. DKA نادر لكن خطير.',optimalTime:'08:00',category2:'مثبط SGLT-2'},

{id:'d022',name:'Dapagliflozin (داباجليفلوزين)',category:'السكري',dose:'10mg',freq:'مرة يومياً',timing:'08:00',food:'بغض النظر عن الطعام',route:'فموي',sideEffects:'التهابات تناسلية، تبول متكرر',contraindications:'GFR<25 لمرضى السكري',renalAdj:'للحماية الكلوية يستمر حتى GFR=25',interactions:'Diuretics, Insulin',mechanism:'مثبط SGLT-2',halfLife:'12 ساعة',blackBox:'',notes:'معتمد أيضاً لقصور القلب وأمراض الكلى بغض النظر عن السكري.',optimalTime:'08:00',category2:'مثبط SGLT-2'},

{id:'d023',name:'Sitagliptin (سيتاجليبتين)',category:'السكري',dose:'100mg',freq:'مرة يومياً',timing:'أي وقت',food:'بغض النظر عن الطعام',route:'فموي',sideEffects:'التهاب أنف وحلق، صداع، نادراً: التهاب بنكرياس',contraindications:'حساسية',renalAdj:'GFR 30-45: 50mg. GFR<30: 25mg',interactions:'Insulin, Sulfonylureas (زيادة نقص السكر)',mechanism:'مثبط DPP-4',halfLife:'12 ساعة',blackBox:'',notes:'محايد للوزن. آمن في المسنين. لا نقص سكر كأحادي علاج.',optimalTime:'أي وقت ثابت',category2:'مثبط DPP-4'},

{id:'d024',name:'Insulin Glargine (إنسولين جلارجين)',category:'السكري',dose:'حسب السكر',freq:'مرة يومياً',timing:'20:00 (أو 08:00 ثابت)',food:'مستقل عن الطعام',route:'حقن تحت الجلد',sideEffects:'نقص سكر، زيادة وزن، ألم في موضع الحقن',contraindications:'نقص سكر',renalAdj:'تقليل الجرعة بحذر',interactions:'Beta-blockers (يخفي الأعراض), Alcohol, Corticosteroids',mechanism:'إنسولين طويل الأمد (24 ساعة)',halfLife:'~24 ساعة',blackBox:'',notes:'لا يُخلط مع أنسابيق أخرى. دوّر مواضع الحقن. Lantus/Toujeo.',optimalTime:'20:00 بوقت ثابت',category2:'إنسولين طويل الأمد'},

// ═══════════════════════════════════════════
// المضادات الحيوية
// ═══════════════════════════════════════════
{id:'d025',name:'Amoxicillin (أموكسيسيلين)',category:'مضادات حيوية',dose:'500mg',freq:'ثلاث مرات يومياً',timing:'كل 8 ساعات',food:'مع أو بدون طعام',route:'فموي',sideEffects:'إسهال، غثيان، طفح، حساسية',contraindications:'حساسية للبنسلين',renalAdj:'GFR 10-30: كل 12 ساعة. <10: كل 24 ساعة',interactions:'Methotrexate, Oral Contraceptives (تقليل فاعلية)',mechanism:'بيتا لاكتام — تثبيط جدار الخلية',halfLife:'1-1.5 ساعة',blackBox:'',notes:'حساسية متقاطعة مع سيفالوسبورين (10%). الكورس الكامل ضروري.',optimalTime:'كل 8 ساعات ثابتة',category2:'بنسلين'},

{id:'d026',name:'Amoxicillin-Clavulanate (أوغمنتين)',category:'مضادات حيوية',dose:'625mg',freq:'ثلاث مرات يومياً',timing:'مع بداية الوجبة',food:'مع الطعام (يقلل الإسهال)',route:'فموي',sideEffects:'إسهال، غثيان، التهاب كبد',contraindications:'حساسية بنسلين، يرقان كبدي سابق من Augmentin',renalAdj:'GFR<30: كل 12 ساعة',interactions:'Warfarin, Methotrexate',mechanism:'بيتا لاكتام + مثبط بيتا لاكتاماز',halfLife:'1-1.5 ساعة',blackBox:'',notes:'أعطِ مع بداية الوجبة لتقليل الأعراض الهضمية.',optimalTime:'مع بداية الوجبة',category2:'بنسلين'},

{id:'d027',name:'Ciprofloxacin (سيبروفلوكساسين)',category:'مضادات حيوية',dose:'500mg',freq:'مرتين يومياً',timing:'كل 12 ساعة',food:'مع أو بدون طعام — تجنب الألبان والمغنيسيوم',route:'فموي',sideEffects:'غثيان، إسهال، تمزق أوتار (نادر)، اضطراب QT',contraindications:'قصور G6PD، حمل، أطفال',renalAdj:'GFR<30: كل 24 ساعة',interactions:'Antacids/Ca/Fe/Mg (يقلل الامتصاص), Theophylline, Warfarin',mechanism:'فلوروكينولون — مثبط DNA Gyrase',halfLife:'4-6 ساعات',blackBox:'تمزق أوتار وتدهور في الوهن العضلي',notes:'فصل الجرعة 2 ساعة عن الأنتاسيدات. مع الكافيين يزيد استثارته.',optimalTime:'08:00 و20:00',category2:'فلوروكينولون'},

{id:'d028',name:'Clarithromycin (كلاريثروميسين)',category:'مضادات حيوية',dose:'250-500mg',freq:'مرتين يومياً',timing:'مع الطعام',food:'مع الطعام',route:'فموي',sideEffects:'غثيان، إسهال، طعم معدني، اضطراب QT',contraindications:'أمراض قلب مع QT طويل، حمل',renalAdj:'GFR<30: تخفيض 50%',interactions:'Statins, Warfarin, Digoxin, QT-drugs, Colchicine',mechanism:'ماكروليد — تثبيط 50S Ribosome',halfLife:'3-7 ساعات',blackBox:'',notes:'تفاعلات دوائية كثيرة. راجع التفاعلات قبل الوصف.',optimalTime:'مع الوجبات',category2:'ماكروليد'},

{id:'d029',name:'Azithromycin (أزيثروميسين)',category:'مضادات حيوية',dose:'500mg',freq:'مرة يومياً × 3-5 أيام',timing:'بعيداً عن الأنتاسيدات',food:'مع أو بدون طعام',route:'فموي',sideEffects:'غثيان، إسهال، اضطراب QT',contraindications:'أمراض قلب مع QT طويل',renalAdj:'لا تعديل',interactions:'Warfarin, QT-prolonging drugs, Antacids (فصل ساعتين)',mechanism:'ماكروليد — 50S',halfLife:'68 ساعة',blackBox:'',notes:'نصف العمر الطويل يسمح بكورس قصير. احذر مرضى QT.',optimalTime:'في أي وقت ثابت',category2:'ماكروليد'},

{id:'d030',name:'Doxycycline (دوكسيسيكلين)',category:'مضادات حيوية',dose:'100mg',freq:'مرتين يومياً',timing:'مع الطعام وكأس ماء كامل — أبقَ واقفاً 30 دقيقة',food:'مع الطعام وماء وفير',route:'فموي',sideEffects:'تهيج مريء، حساسية ضوئية، غثيان',contraindications:'حمل، رضاعة، أطفال <8 سنوات',renalAdj:'لا تعديل',interactions:'Antacids, Fe, Ca (يقلل الامتصاص), Warfarin, Oral contraceptives',mechanism:'تيتراسيكلين — تثبيط 30S',halfLife:'15-25 ساعة',blackBox:'',notes:'لا تستلق بعد الجرعة مباشرة. واقٍ من الشمس ضروري.',optimalTime:'مع الوجبات 08:00 و20:00',category2:'تيتراسيكلين'},

{id:'d031',name:'Metronidazole (ميترونيدازول)',category:'مضادات حيوية',dose:'400-500mg',freq:'ثلاث مرات يومياً',timing:'مع الطعام',food:'مع الطعام',route:'فموي',sideEffects:'غثيان، طعم معدني، ألم رأس، تخدر أطراف (طويل الأمد)',contraindications:'الثلث الأول من الحمل، شرب الكحول',renalAdj:'احتياط مع غسيل الكلى',interactions:'Alcohol (Disulfiram reaction), Warfarin, Lithium',mechanism:'نيتروإيميدازول — أضرار DNA الطفيليات/الحيوانات',halfLife:'8 ساعة',blackBox:'',notes:'ممنوع الكحول أثناء الدواء و48 ساعة بعده.',optimalTime:'مع الوجبات',category2:'نيتروإيميدازول'},

{id:'d032',name:'Trimethoprim-Sulfamethoxazole (كوتريموكسازول)',category:'مضادات حيوية',dose:'160/800mg',freq:'مرتين يومياً',timing:'مع الطعام',food:'مع الطعام',route:'فموي',sideEffects:'طفح (Stevens-Johnson نادر)، نقص بوتاسيوم، حساسية كلوية',contraindications:'حساسية سلفا، حمل قريب الولادة، نقص G6PD',renalAdj:'GFR 15-30: تخفيض. <15: تجنب',interactions:'Warfarin, Methotrexate, Phenytoin, ACE inhibitors (فرط K)',mechanism:'مثبط Dihydrofolate Reductase وDihydropteroate Synthase',halfLife:'10 ساعة',blackBox:'',notes:'شرب ماء كثير. إبلاغ عن أي طفح فوراً.',optimalTime:'مع الوجبات',category2:'سلفاميد'},

// ═══════════════════════════════════════════
// أدوية الجهاز الهضمي
// ═══════════════════════════════════════════
{id:'d033',name:'Omeprazole (أوميبرازول)',category:'الجهاز الهضمي',dose:'20-40mg',freq:'مرة يومياً',timing:'قبل الإفطار بـ 30-60 دقيقة',food:'قبل الطعام',route:'فموي',sideEffects:'صداع، إسهال، نقص Mg وB12 (طويل الأمد)، زيادة الكسور',contraindications:'حساسية لـ PPI',renalAdj:'لا تعديل',interactions:'Clopidogrel (يقلل فاعليته), Methotrexate, Warfarin',mechanism:'مثبط مضخة البروتون',halfLife:'1-2 ساعة (تأثير 24 ساعة)',blackBox:'',notes:'أفضل تأثير قبل الإفطار بنصف ساعة. تجنب الاستخدام الطويل بلا مؤشر.',optimalTime:'قبل الإفطار بـ 30 دقيقة',category2:'PPI'},

{id:'d034',name:'Pantoprazole (بانتوبرازول)',category:'الجهاز الهضمي',dose:'20-40mg',freq:'مرة يومياً',timing:'قبل الإفطار بـ 30 دقيقة',food:'قبل الطعام',route:'فموي',sideEffects:'صداع، إسهال، نقص Mg',contraindications:'حساسية PPI',renalAdj:'لا تعديل',interactions:'أقل تأثيراً على Clopidogrel مقارنة بـ Omeprazole',mechanism:'مثبط مضخة البروتون',halfLife:'1 ساعة',blackBox:'',notes:'مفضل مع Clopidogrel بدلاً من Omeprazole.',optimalTime:'قبل الإفطار بـ 30 دقيقة',category2:'PPI'},

{id:'d035',name:'Ranitidine بديل: Famotidine (فاموتيدين)',category:'الجهاز الهضمي',dose:'20-40mg',freq:'مرة-مرتين يومياً',timing:'22:00 أو قبل الوجبة',food:'بغض النظر عن الطعام',route:'فموي',sideEffects:'صداع، إمساك',contraindications:'حساسية',renalAdj:'GFR<50: تخفيض للنصف',interactions:'أقل تفاعلات من PPIs',mechanism:'حاصر H2',halfLife:'2.5-3.5 ساعة',blackBox:'',notes:'Ranitidine سُحب من الأسواق. Famotidine البديل الآمن.',optimalTime:'22:00',category2:'حاصر H2'},

{id:'d036',name:'Ondansetron (أوندانسيترون)',category:'الجهاز الهضمي',dose:'4-8mg',freq:'كل 8 ساعات عند الحاجة',timing:'قبل العلاج الكيماوي أو عند الغثيان',food:'بغض النظر عن الطعام',route:'فموي / وريدي',sideEffects:'إمساك، صداع، إطالة QT',contraindications:'انسداد الأمعاء، اضطراب QT',renalAdj:'لا تعديل',interactions:'QT-prolonging drugs, Apomorphine',mechanism:'مضاد 5-HT3',halfLife:'3-4 ساعات',blackBox:'',notes:'فعال لغثيان ما بعد الجراحة والعلاج الكيماوي.',optimalTime:'30 دقيقة قبل العلاج أو عند الحاجة',category2:'مضاد غثيان'},

{id:'d037',name:'Metoclopramide (ميتوكلوبراميد)',category:'الجهاز الهضمي',dose:'10mg',freq:'ثلاث مرات يومياً',timing:'قبل الوجبات بـ 30 دقيقة',food:'قبل الطعام',route:'فموي / وريدي',sideEffects:'نعاس، أعراض خارج هرمية، فرط برولاكتين',contraindications:'انسداد أو نزيف هضمي، الصرع، باركنسون',renalAdj:'GFR<40: تخفيض النصف',interactions:'Opioids, Anticholinergics, Antipsychotics',mechanism:'مضاد دوبامين (محفز حركية)',halfLife:'4-6 ساعات',blackBox:'حركات لا إرادية مع الاستخدام الطويل',notes:'لا تتجاوز 5 أيام متواصلة. خطر التأثيرات خارج الهرمية.',optimalTime:'قبل الوجبات 30 دقيقة',category2:'محرك حركة هضمية'},

{id:'d038',name:'Lactulose (لاكتولوز)',category:'الجهاز الهضمي',dose:'15-30ml',freq:'مرة-مرتين يومياً',timing:'08:00',food:'مع السوائل',route:'فموي',sideEffects:'انتفاخ، غازات، إسهال بجرعات عالية',contraindications:'انسداد أمعاء',renalAdj:'لا تعديل',interactions:'Antacids, Neomycin',mechanism:'مسهل أسموزي + تحمض القولون',halfLife:'لا ينطبق',blackBox:'',notes:'اشرب سوائل كافية. تأثير قد يظهر بعد 24-48 ساعة.',optimalTime:'08:00',category2:'ملين'},

// ═══════════════════════════════════════════
// أدوية الجهاز التنفسي
// ═══════════════════════════════════════════
{id:'d039',name:'Salbutamol Inhaler (بخاخ فنتولين - Ventolin)',category:'الجهاز التنفسي',dose:'100-200mcg',freq:'عند الحاجة (PRN)',timing:'عند بدء ضيق التنفس',food:'لا علاقة',route:'استنشاق',sideEffects:'رجفة، خفقان، صداع، نقص بوتاسيوم (جرعات عالية)',contraindications:'حساسية',renalAdj:'لا تعديل',interactions:'Beta-blockers (تقليل فاعلية), Digoxin, Diuretics',mechanism:'ناهض بيتا 2 قصير الأمد (SABA)',halfLife:'3-8 ساعة',blackBox:'',notes:'الموسع السريع. إذا احتاجه أكثر من مرتين أسبوعياً — ضبط العلاج الصيانة.',optimalTime:'عند الحاجة',category2:'موسع قصبي سريع'},

{id:'d040',name:'Salmeterol/Formoterol (سالميترول)',category:'الجهاز التنفسي',dose:'حسب الجهاز',freq:'مرتين يومياً',timing:'08:00 و20:00',food:'لا علاقة',route:'استنشاق',sideEffects:'خفقان، رجفة',contraindications:'لا يُستخدم وحده بدون ICS في الربو',renalAdj:'لا تعديل',interactions:'Beta-blockers, Diuretics, MAOIs',mechanism:'ناهض بيتا 2 طويل الأمد (LABA)',halfLife:'10-14 ساعة',blackBox:'خطر زيادة الوفيات في الربو إذا بدون ICS',notes:'دائماً مع كورتيزون استنشاق (ICS) في الربو. ليس للنوبات الحادة.',optimalTime:'08:00 و20:00 ثابتة',category2:'موسع قصبي طويل'},

{id:'d041',name:'Fluticasone Inhaled (فلوتيكازون استنشاق)',category:'الجهاز التنفسي',dose:'100-500mcg',freq:'مرتين يومياً',timing:'08:00 و20:00',food:'لا علاقة',route:'استنشاق',sideEffects:'التهاب فم وحلق، بحة صوت',contraindications:'حساسية',renalAdj:'لا تعديل',interactions:'CYP3A4 inhibitors (Ketoconazole, Ritonavir)',mechanism:'كورتيكوستيرويد استنشاق (ICS)',halfLife:'7.8 ساعة',blackBox:'',notes:'اغسل الفم بعد كل جرعة لمنع الالتهابات الفطرية.',optimalTime:'08:00 و20:00 — اغسل الفم بعدها',category2:'كورتيكوستيرويد استنشاق'},

{id:'d042',name:'Montelukast (مونتيلوكاست)',category:'الجهاز التنفسي',dose:'10mg',freq:'مرة يومياً',timing:'20:00 22:00',food:'بغض النظر عن الطعام',route:'فموي',sideEffects:'صداع، ألم بطن، أحلام غريبة، تغيرات مزاجية',contraindications:'حساسية',renalAdj:'لا تعديل',interactions:'Phenobarbital, Rifampicin (تقليل مستوى)',mechanism:'مضاد مستقبلات ليكوترين (LTRA)',halfLife:'2.7-5.5 ساعة',blackBox:'تأثيرات نفسية وعصبية: أفكار انتحارية (نادر)',notes:'يُعطى 20:00. فعال في حساسية المسالك مع الربو.',optimalTime:'20:00 22:00',category2:'مضاد لوكوترين'},

// ═══════════════════════════════════════════
// أدوية الغدة الدرقية
// ═══════════════════════════════════════════
{id:'d043',name:'Levothyroxine (ليفوثيروكسين)',category:'الغدد الصماء',dose:'25-200mcg',freq:'مرة يومياً',timing:'08:00 على معدة فارغة — 30-60 دقيقة قبل الأكل',food:'على معدة فارغة — تجنب الكالسيوم والحديد والقهوة',route:'فموي',sideEffects:'خفقان، رجفة، فقدان وزن، أرق (جرعة زائدة)',contraindications:'احتشاء حاد، فشل قشرة الكظر غير المعالج',renalAdj:'لا تعديل',interactions:'Calcium, Iron, Antacids (يقلل الامتصاص — فصل 4 ساعات), Warfarin, Cholestyramine',mechanism:'هرمون درقي اصطناعي T4',halfLife:'7 أيام',blackBox:'',notes:'ثبات الوقت والجرعة مهم جداً. مراقبة TSH كل 6-12 شهراً.',optimalTime:'08:00 على معدة فارغة (30-60 دقيقة قبل الإفطار)',category2:'هرمون درقي'},

{id:'d044',name:'Carbimazole / Methimazole (كاربيمازول)',category:'الغدد الصماء',dose:'5-40mg',freq:'مرة-ثلاث مرات يومياً',timing:'مع الطعام',food:'مع الطعام',route:'فموي',sideEffects:'قمع نخاع العظم، طفح، تأثير درقية (hypothyroidism)',contraindications:'فرط حساسية، حمل الأول (يفضل PTU)',renalAdj:'لا تعديل',interactions:'Warfarin, Digoxin, Theophylline',mechanism:'مثبط synthesis هرمون الدرقية',halfLife:'4-8 ساعات',blackBox:'',notes:'ابلغ عن حمى أو التهاب حلق فوراً (قمع نخاع). فحص CBC.',optimalTime:'مع الوجبات',category2:'مثبط الدرقية'},

// ═══════════════════════════════════════════
// أدوية الأعصاب والنفسية
// ═══════════════════════════════════════════
{id:'d045',name:'Sertraline (سيرترالين)',category:'الصحة النفسية',dose:'50-200mg',freq:'مرة يومياً',timing:'08:00 (أو 20:00 لو أرق)',food:'مع أو بدون طعام',route:'فموي',sideEffects:'غثيان (في البداية)، أرق، صداع، خلل جنسي، زيادة وزن',contraindications:'مع MAOIs، اضطراب ثنائي القطب غير محمي',renalAdj:'لا تعديل',interactions:'MAOIs (14 يوم فصل), Tramadol, Lithium, Warfarin',mechanism:'مثبط انتقاء السيروتونين (SSRI)',halfLife:'26 ساعة',blackBox:'زيادة أفكار انتحارية عند صغار السن',notes:'تأثير بعد 2-4 أسابيع. لا توقف فجأة.',optimalTime:'08:00',category2:'SSRI'},

{id:'d046',name:'Escitalopram (إسسيتالوبرام)',category:'الصحة النفسية',dose:'10-20mg',freq:'مرة يومياً',timing:'08:00 أو 20:00',food:'مع أو بدون طعام',route:'فموي',sideEffects:'غثيان، أرق، دوخة، خلل جنسي',contraindications:'MAOIs، QT طويل',renalAdj:'لا تعديل',interactions:'MAOIs, QT-prolonging drugs, Tramadol',mechanism:'SSRI انتقائي عالي',halfLife:'27-32 ساعة',blackBox:'أفكار انتحارية صغار السن',notes:'من أكثر SSRIs تحملاً. تأثير بعد 2-4 أسابيع.',optimalTime:'08:00 أو 20:00 ثابت',category2:'SSRI'},

{id:'d047',name:'Amitriptyline (أميتريبتيلين)',category:'الصحة النفسية',dose:'10-150mg',freq:'مرة يومياً (20:00)',timing:'22:00 (منوم)',food:'مع الطعام',route:'فموي',sideEffects:'نعاس، جفاف فم، إمساك، احتباس بول، تسرع قلب',contraindications:'احتشاء حديث، اضطراب QT، جلوكوما زاوية ضيقة',renalAdj:'احتياط',interactions:'MAOIs, Tramadol, Anticholinergics, Alcohol',mechanism:'مثبط TCA — سيروتونين ونورأدرينالين',halfLife:'10-50 ساعة',blackBox:'سمية قلبية بجرعات عالية',notes:'جرعات منخفضة لألم الأعصاب والصداع النصفي الوقائي.',optimalTime:'22:00',category2:'TCA'},

{id:'d048',name:'Lithium Carbonate (ليثيوم)',category:'الصحة النفسية',dose:'400-1200mg',freq:'مرتين-ثلاث مرات يومياً',timing:'مع الطعام',food:'مع الطعام وسوائل كافية',route:'فموي',sideEffects:'رجفة، كثرة تبول، زيادة وزن، قصور درقية، نقص كلوي',contraindications:'قصور كلوي شديد، قلب مضطرب',renalAdj:'تعديل دقيق — مراقبة مستوى الدواء',interactions:'NSAIDs, ACE inhibitors, Diuretics (يرفعون مستوى الليثيوم)',mechanism:'يستقر مزاج — آلية غير مفهومة تماماً',halfLife:'18-24 ساعة',blackBox:'نطاق علاجي ضيق 0.6-1.2 mEq/L — سمية عالية',notes:'ثبات السوائل والملح مهم. راقب مستوى الليثيوم كل 3-6 أشهر.',optimalTime:'مع الوجبات — ثبات الجدول',category2:'مثبت مزاج'},

{id:'d049',name:'Gabapentin (جابابنتين)',category:'الأعصاب',dose:'300-3600mg',freq:'ثلاث مرات يومياً',timing:'كل 8 ساعات',food:'مع أو بدون طعام',route:'فموي',sideEffects:'نعاس، دوخة، وذمة، زيادة وزن',contraindications:'حساسية',renalAdj:'GFR 30-60: كل 12 ساعة. GFR<30: كل 24 ساعة بجرعة أقل',interactions:'Opioids (زيادة اكتئاب تنفسي), Antacids (يقلل الامتصاص)',mechanism:'يرتبط بقناة كالسيوم Alpha2-delta',halfLife:'5-7 ساعات',blackBox:'',notes:'ابدأ بجرعة منخفضة وزد تدريجياً. لا توقف فجأة.',optimalTime:'كل 8 ساعات ثابتة',category2:'مضاد صرع/ألم'},

{id:'d050',name:'Pregabalin (بريجابالين)',category:'الأعصاب',dose:'75-300mg',freq:'مرتين يومياً',timing:'08:00 و20:00',food:'مع أو بدون طعام',route:'فموي',sideEffects:'نعاس، دوخة، وذمة، زيادة وزن، ضبابية',contraindications:'حساسية',renalAdj:'GFR 30-60: نصف الجرعة. GFR<30: ربع الجرعة',interactions:'Opioids, Alcohol, CNS depressants',mechanism:'يرتبط بقناة كالسيوم Alpha2-delta',halfLife:'6 ساعات',blackBox:'خطر إدمان (مادة خاضعة للرقابة)',notes:'لا توقف فجأة. تقليل تدريجي.',optimalTime:'08:00 و20:00',category2:'مضاد صرع/ألم'},

{id:'d051',name:'Phenytoin (فينيتوين)',category:'الأعصاب',dose:'300-400mg',freq:'مرة-مرتين يومياً',timing:'مع الطعام',food:'مع الطعام — ثبات التوقيت',route:'فموي',sideEffects:'تضخم لثة، شعر زائد، ترنح، رأرأة، انخفاض Ca',contraindications:'حساسية، انسداد AV',renalAdj:'لا تعديل — لكن مراقبة مستوى مهمة',interactions:'Warfarin, Carbamazepine, Phenobarbital, OCP, Folate',mechanism:'مثبط قنوات صوديوم',halfLife:'7-42 ساعة (غير خطي)',blackBox:'',notes:'نطاق علاجي ضيق 10-20 mcg/ml. تفاعلات دوائية كثيرة. فولات ضروري.',optimalTime:'مع الوجبات — وقت ثابت',category2:'مضاد صرع'},

{id:'d052',name:'Levodopa/Carbidopa (ليفودوبا)',category:'الأعصاب',dose:'100/25mg',freq:'ثلاث مرات يومياً',timing:'قبل الطعام بـ 30-60 دقيقة',food:'قبل الطعام — تجنب البروتين العالي وقت الجرعة',route:'فموي',sideEffects:'غثيان، دوخة وضعية، حركات لا إرادية، ذهان',contraindications:'جلوكوما زاوية ضيقة، MAOIs',renalAdj:'احتياط',interactions:'MAOIs (أزمة ضغطية), Antipsychotics (تضاد), Iron (يقلل امتصاص)',mechanism:'ناقل عصبي مباشر — دوبامين في الدماغ',halfLife:'1-2 ساعة',blackBox:'',notes:'تجنب الوجبات الغنية بالبروتين وقت الجرعة. الظاهرة "on-off" مع الوقت.',optimalTime:'قبل الوجبات 30-60 دقيقة',category2:'مضاد باركنسون'},

// ═══════════════════════════════════════════
// مسكنات الألم
// ═══════════════════════════════════════════
{id:'d053',name:'Paracetamol/Acetaminophen (باراسيتامول)',category:'المسكنات',dose:'500-1000mg',freq:'كل 4-6 ساعات (max 4g/day)',timing:'عند الألم أو الحرارة',food:'مع أو بدون طعام',route:'فموي / وريدي',sideEffects:'آمن بالجرعات المعتادة. سمية كبدية بالجرعات الزائدة',contraindications:'فشل كبدي، جرعة تفوق 4g/يوم',renalAdj:'GFR<30: كل 8 ساعات',interactions:'Warfarin (جرعات عالية تطيل INR), Alcohol (سمية كبدية)',mechanism:'مثبط COX مركزي + مستقبلات cannabinoid',halfLife:'2-3 ساعات',blackBox:'',notes:'الجرعة القصوى 4g/يوم (2g في الكبد الضعيف). راقب الجرعات المجمعة.',optimalTime:'عند الحاجة',category2:'مسكن ألم'},

{id:'d054',name:'Ibuprofen (إيبوبروفين)',category:'المسكنات',dose:'200-800mg',freq:'ثلاث مرات يومياً',timing:'مع الطعام',food:'مع الطعام',route:'فموي',sideEffects:'نزيف هضمي، ارتفاع ضغط، قصور كلوي، احتباس ماء',contraindications:'قرحة نشطة، قصور كلوي/قلبي، الثلث الثالث حمل',renalAdj:'تجنب مع GFR<30',interactions:'Warfarin, ACE inhibitors (تقليل تأثير), Lithium, Methotrexate',mechanism:'مثبط COX 1 وCOX 2 غير انتقائي',halfLife:'2 ساعة',blackBox:'',notes:'أضف PPI مع الاستخدام الطويل. تجنب مع القلب والكلى الضعيفة.',optimalTime:'مع الوجبات',category2:'NSAID'},

{id:'d055',name:'Naproxen (نابروكسين)',category:'المسكنات',dose:'250-500mg',freq:'مرتين يومياً',timing:'مع الطعام',food:'مع الطعام',route:'فموي',sideEffects:'نزيف هضمي، قصور كلوي، ارتفاع ضغط',contraindications:'مثل Ibuprofen',renalAdj:'تجنب مع GFR<30',interactions:'مثل Ibuprofen',mechanism:'مثبط COX غير انتقائي',halfLife:'12-17 ساعة',blackBox:'',notes:'جرعتان يومياً فقط. مفيد في التهاب المفاصل.',optimalTime:'مع وجبتي الصباح والمساء',category2:'NSAID'},

{id:'d056',name:'Tramadol (ترامادول)',category:'المسكنات',dose:'50-100mg',freq:'كل 6-8 ساعات عند الحاجة (max 400mg/day)',timing:'عند الحاجة',food:'مع أو بدون طعام',route:'فموي',sideEffects:'غثيان، إمساك، نعاس، دوخة، إدمان',contraindications:'صرع غير مسيطر عليه، مع MAOIs، حمل',renalAdj:'GFR<30: كل 12 ساعة',interactions:'MAOIs, SSRIs (متلازمة سيروتونين), Alcohol, CNS depressants',mechanism:'ناهض أوبيويد جزئي + مثبط SNRI',halfLife:'5-7 ساعة',blackBox:'إدمان، صرع، متلازمة سيروتونين',notes:'خطر الإدمان. لا مع الصرع. تفاعل خطير مع SSRIs.',optimalTime:'عند الحاجة — بأقل جرعة فعالة',category2:'أوبيويد جزئي'},

// ═══════════════════════════════════════════
// أدوية الروماتيزم والعظام
// ═══════════════════════════════════════════
{id:'d057',name:'Methotrexate (ميثوتريكسات)',category:'الروماتيزم',dose:'7.5-25mg',freq:'مرة أسبوعياً فقط',timing:'يوم ثابت أسبوعياً',food:'مع أو بدون طعام',route:'فموي / حقن',sideEffects:'غثيان، رفع كبد، تليف كبدي، تليف رئوي، قمع نخاع',contraindications:'حمل، كبد شديد، GFR<30، نقص مناعة شديد',renalAdj:'GFR<30: ممنوع',interactions:'NSAIDs, Cotrimoxazole (يزيد السمية بشكل خطير), PPIs, Penicillin',mechanism:'مضاد ميتابوليت — مثبط Dihydrofolate Reductase',halfLife:'3-10 ساعة',blackBox:'سمية كبدية، رئوية، نخاع، ماسخ للجنين',notes:'مرة في الأسبوع فقط! أخطاء الجرعة اليومية قاتلة. حمض الفوليك يومياً ماعدا يوم MTX.',optimalTime:'يوم ثابت أسبوعياً',category2:'مثبط مناعة / DMARD'},

{id:'d058',name:'Hydroxychloroquine (هيدروكسي كلوروكين)',category:'الروماتيزم',dose:'200-400mg',freq:'مرة يومياً',timing:'مع الطعام',food:'مع الطعام',route:'فموي',sideEffects:'غثيان، تغير رؤية (اعتلال شبكية نادر)',contraindications:'أمراض شبكية، حساسية',renalAdj:'احتياط مع GFR<10',interactions:'Amiodarone (QT), Digoxin',mechanism:'مضاد ملاريا / ذئبة — تثبيط TLR',halfLife:'40-50 يوم',blackBox:'',notes:'فحص عيون سنوي بعد 5 سنوات. آمن في الحمل.',optimalTime:'مع الطعام',category2:'DMARD'},

{id:'d059',name:'Alendronate (أليندرونات)',category:'العظام',dose:'70mg',freq:'مرة أسبوعياً',timing:'صباح أول الأسبوع — على معدة فارغة',food:'على معدة فارغة مع كأس ماء كامل — لا تستلق 30 دقيقة',route:'فموي',sideEffects:'تهيج مريء، ألم بطن، اضطرابات مريئية',contraindications:'قصور كلوي (GFR<35)، اضطراب بلع، مريء غير طبيعي',renalAdj:'GFR<35: ممنوع',interactions:'Calcium, Iron, Antacids (يقلل الامتصاص)',mechanism:'بيسفوسفونات — تثبيط Osteoclast',halfLife:'10+ سنوات في العظم',blackBox:'تنخر عظم الفك (نادر)، كسر فخذ غير نمطي',notes:'ابقَ واقفاً أو جالساً 30 دقيقة بعد الجرعة. لا تأكل لـ 30 دقيقة بعدها.',optimalTime:'صباح الجمعة أو أي يوم ثابت أسبوعياً على معدة فارغة',category2:'بيسفوسفونات'},

{id:'d060',name:'Colchicine (كولشيسين)',category:'الروماتيزم',dose:'0.5-1mg',freq:'مرة-مرتين يومياً',timing:'مع أو بدون طعام',food:'مع أو بدون طعام',route:'فموي',sideEffects:'إسهال، غثيان، ألم بطن، قمع نخاع (جرعات عالية)',contraindications:'قصور كلوي/كبدي شديد',renalAdj:'GFR<30: تخفيض الجرعة',interactions:'Clarithromycin, Cyclosporine, Statins (زيادة سمية خطيرة)',mechanism:'يثبط حركة الخلايا وتجميع التيوبيولين',halfLife:'27-31 ساعة',blackBox:'',notes:'للنقرس الحاد: 1mg ثم 0.5mg بعد ساعة. تفاعل خطير مع Clarithromycin.',optimalTime:'أي وقت ثابت',category2:'مضاد النقرس'},

{id:'d061',name:'Allopurinol (ألوبيورينول)',category:'الروماتيزم',dose:'100-300mg',freq:'مرة يومياً',timing:'بعد الطعام',food:'بعد الطعام',route:'فموي',sideEffects:'طفح (يصل لـ SJS)، رفع كبد، غثيان',contraindications:'حساسية، نوبة نقرس حادة',renalAdj:'GFR 10-20: 100mg. <10: 100mg كل 48 ساعة',interactions:'Azathioprine, 6-MP (زيادة سمية خطيرة), Warfarin, Amoxicillin',mechanism:'مثبط Xanthine Oxidase',halfLife:'1-2 ساعة (أوكسيبورينول 23 ساعة)',blackBox:'متلازمة Stevens-Johnson',notes:'لا تبدأ في النوبة الحادة. تدرج في الجرعة. فحص HLA-B*58:01 قبل في آسيويين.',optimalTime:'بعد الطعام',category2:'مضاد النقرس'},

// ═══════════════════════════════════════════
// المضادات الفطرية والطفيليات
// ═══════════════════════════════════════════
{id:'d062',name:'Fluconazole (فلوكونازول)',category:'مضادات فطرية',dose:'50-400mg',freq:'مرة يومياً',timing:'أي وقت',food:'مع أو بدون طعام',route:'فموي',sideEffects:'غثيان، صداع، رفع كبد، اضطراب QT',contraindications:'حساسية، مع Terfenadine/Cisapride',renalAdj:'GFR<50: تخفيض 50%',interactions:'Warfarin, Phenytoin, Statins, Midazolam, Cyclosporine, QT-drugs',mechanism:'مثبط CYP51 — تثبيط إرجوستيرول',halfLife:'30 ساعة',blackBox:'',notes:'تفاعلات دوائية كثيرة عبر CYP450. للمهبلي: جرعة 150mg واحدة.',optimalTime:'أي وقت ثابت',category2:'أزول'},

{id:'d063',name:'Mebendazole (ميبنيدازول)',category:'مضادات طفيليات',dose:'100-500mg',freq:'مرتان لـ ديدان — 3 أيام للأسكاريس',timing:'مع الطعام',food:'مع الطعام (يزيد الامتصاص)',route:'فموي',sideEffects:'غثيان، ألم بطن خفيف',contraindications:'حمل (الأول)، حساسية',renalAdj:'لا تعديل',interactions:'Cimetidine',mechanism:'تثبيط تكوين الأنابيب الدقيقة',halfLife:'3-9 ساعة',blackBox:'',notes:'علاج الديدان. جرعة ثانية بعد أسبوعين لمنع الإعادة.',optimalTime:'مع الوجبة',category2:'مضاد ديدان'},

// ═══════════════════════════════════════════
// مكملات ونقص عناصر
// ═══════════════════════════════════════════
{id:'d064',name:'Iron Ferrous Sulfate (حديد فيروس سلفات)',category:'مكملات',dose:'200-300mg',freq:'مرتين-ثلاث مرات يومياً',timing:'على معدة فارغة أو مع فيتامين C',food:'على معدة فارغة أو مع فيتامين C لتحسين الامتصاص',route:'فموي',sideEffects:'إمساك، غثيان، برازأسود، إسهال',contraindications:'فرط الحديد، Hemochromatosis',renalAdj:'لا تعديل',interactions:'Levothyroxine, Ciprofloxacin, Doxycycline (يقلل الامتصاص — فصل ساعتين), Antacids',mechanism:'تعويض نقص الحديد لتخليق الهيموغلوبين',halfLife:'لا ينطبق',blackBox:'',notes:'البراز الأسود طبيعي. تحسن Hb بعد 2-4 أسابيع. استمر 3-6 أشهر بعد تحسن الأنيميا.',optimalTime:'على معدة فارغة مع عصير برتقال (فيتامين C)',category2:'معدن - حديد'},

{id:'d065',name:'Calcium Carbonate (كالسيوم كربونات)',category:'مكملات',dose:'500-1000mg عنصري',freq:'مرتين يومياً',timing:'مع الطعام (يحتاج حامض للامتصاص)',food:'مع الطعام',route:'فموي',sideEffects:'إمساك، غازات، فرط كالسيوم (بجرعات عالية)',contraindications:'فرط كالسيوم، حصى كلى كالسيوم',renalAdj:'احتياط مع GFR<30',interactions:'Levothyroxine, Iron, Fluoroquinolones, Bisphosphonates (يقلل الامتصاص)',mechanism:'تعويض كالسيوم + أنتاسيد',halfLife:'لا ينطبق',blackBox:'',notes:'فصل الجرعة 2-4 ساعات عن الأدوية المتأثرة.',optimalTime:'مع الوجبات',category2:'معدن - كالسيوم'},

{id:'d066',name:'Vitamin D3 (فيتامين د3)',category:'مكملات',dose:'1000-5000 IU',freq:'مرة يومياً أو أسبوعياً',timing:'مع الوجبة الدسمة',food:'مع طعام يحتوي على دهون',route:'فموي',sideEffects:'آمن بالجرعات المعتادة. فرط كالسيوم بجرعات زائدة',contraindications:'فرط كالسيوم، حصى كلى',renalAdj:'استخدم Calcitriol مع GFR<30 بدلاً من D3',interactions:'Thiazide diuretics (فرط كالسيوم), Cholestyramine, Corticosteroids',mechanism:'يعزز امتصاص الكالسيوم والفوسفور',halfLife:'24 ساعة',blackBox:'',notes:'مع دهون يمتص أفضل.',optimalTime:'مع أكبر وجبة في اليوم',category2:'فيتامين'},

{id:'d067',name:'Folic Acid (حمض الفوليك)',category:'مكملات',dose:'0.4-5mg',freq:'مرة يومياً',timing:'أي وقت',food:'مع أو بدون طعام',route:'فموي',sideEffects:'نادرة',contraindications:'سرطان معتمد على حمض الفوليك (احتياط)',renalAdj:'لا تعديل',interactions:'Methotrexate, Phenytoin, Sulfasalazine',mechanism:'ضروري لتخليق DNA وتكوين خلايا الدم',halfLife:'لا ينطبق',blackBox:'',notes:'ضروري في الحمل (قبل الحمل وأوله). مع Methotrexate يومياً ماعدا يوم الجرعة.',optimalTime:'أي وقت',category2:'فيتامين'},

{id:'d068',name:'Vitamin B12 / Cyanocobalamin',category:'مكملات',dose:'500-1000mcg',freq:'مرة يومياً',timing:'أي وقت',food:'مع أو بدون طعام',route:'فموي / حقن',sideEffects:'نادرة',contraindications:'حساسية للكوبالت',renalAdj:'لا تعديل',interactions:'Metformin, PPIs, Colchicine (يقلل الامتصاص)',mechanism:'ضروري لتكوين الميلين والخلايا الحمراء',halfLife:'لا ينطبق',blackBox:'',notes:'نقص شائع مع Metformin وPPIs طويلة الأمد.',optimalTime:'أي وقت',category2:'فيتامين'},

// ═══════════════════════════════════════════
// أدوية المسالك البولية
// ═══════════════════════════════════════════
{id:'d069',name:'Tamsulosin (تامسولوسين)',category:'المسالك البولية',dose:'0.4mg',freq:'مرة يومياً',timing:'بعد نفس الوجبة يومياً',food:'بعد الطعام',route:'فموي',sideEffects:'دوخة وضعية، سيلان أنف، قذف رجعي',contraindications:'ضغط منخفض، مع PDE5 inhibitors بحذر',renalAdj:'GFR<10: احتياط',interactions:'PDE5 inhibitors (Sildenafil) — انخفاض ضغط شديد',mechanism:'حاصر ألفا 1 انتقائي',halfLife:'9-15 ساعة',blackBox:'',notes:'قف ببطء من الجلوس. يُعطى 20:00 لتقليل الدوخة.',optimalTime:'20:00',category2:'حاصر ألفا'},

{id:'d070',name:'Finasteride (فيناستيريد)',category:'المسالك البولية',dose:'5mg',freq:'مرة يومياً',timing:'أي وقت',food:'مع أو بدون طعام',route:'فموي',sideEffects:'خلل جنسي، انخفاض PSA، نادراً: اكتئاب',contraindications:'حمل (تماس الجلدي خطر), نساء',renalAdj:'لا تعديل',interactions:'لا تفاعلات مهمة',mechanism:'مثبط 5-alpha Reductase',halfLife:'5-7 ساعة',blackBox:'',notes:'يخفض PSA 50% — اضرب القياس ×2 عند التقييم.',optimalTime:'أي وقت ثابت',category2:'مثبط 5-alpha Reductase'},

// ═══════════════════════════════════════════
// أدوية الحساسية
// ═══════════════════════════════════════════
{id:'d071',name:'Cetirizine (سيتيريزين)',category:'الحساسية',dose:'10mg',freq:'مرة يومياً',timing:'20:00 (يسبب نعاساً خفيفاً)',food:'مع أو بدون طعام',route:'فموي',sideEffects:'نعاس خفيف، جفاف فم',contraindications:'قصور كلوي شديد بدون تعديل',renalAdj:'GFR<30: 5mg يومياً',interactions:'Alcohol (زيادة نعاس), CNS depressants',mechanism:'مضاد H1 الجيل الثاني',halfLife:'8-10 ساعة',blackBox:'',notes:'أقل نعاساً من الجيل الأول. يمكن تناوله 08:00 لو لا نعاس.',optimalTime:'20:00',category2:'مضاد هيستامين'},

{id:'d072',name:'Loratadine (لوراتادين)',category:'الحساسية',dose:'10mg',freq:'مرة يومياً',timing:'08:00',food:'مع أو بدون طعام',route:'فموي',sideEffects:'صداع، جفاف فم (نادر)',contraindications:'حساسية',renalAdj:'GFR<30: كل 48 ساعة',interactions:'Ketoconazole, Erythromycin (يرفع مستوى)',mechanism:'مضاد H1 الجيل الثاني',halfLife:'8-14 ساعة',blackBox:'',notes:'لا يسبب نعاساً تقريباً. مناسب لقيادة السيارة.',optimalTime:'08:00',category2:'مضاد هيستامين'},

{id:'d073',name:'Fexofenadine (فيكسوفينادين)',category:'الحساسية',dose:'120-180mg',freq:'مرة يومياً',timing:'08:00 بعيداً عن عصير الجريب فروت',food:'بعيداً عن عصير الجريب فروت والبرتقال والتفاح',route:'فموي',sideEffects:'صداع، غثيان',contraindications:'حساسية',renalAdj:'GFR<30: تخفيض',interactions:'Antacids (Al/Mg), Fruit juices (يقلل الامتصاص)',mechanism:'مضاد H1 الجيل الثالث',halfLife:'11-15 ساعة',blackBox:'',notes:'تجنب عصائر الفاكهة مع الجرعة. لا نعاس.',optimalTime:'08:00 بعيداً عن العصائر',category2:'مضاد هيستامين'},

// ═══════════════════════════════════════════
// الكورتيكوستيرويدات
// ═══════════════════════════════════════════
{id:'d074',name:'Prednisolone (بريدنيزولون)',category:'كورتيكوستيرويدات',dose:'5-60mg',freq:'مرة يومياً (أو مقسمة)',timing:'08:00 08:00',food:'مع الطعام',route:'فموي',sideEffects:'رفع سكر، ارتفاع ضغط، هشاشة عظام، كبت مناعة، كتاراكت، زيادة وزن',contraindications:'عدوى فطرية جهازية غير معالجة',renalAdj:'لا تعديل',interactions:'NSAIDs (نزيف هضمي), Warfarin, Antidiabetics, Vaccines حية',mechanism:'كورتيكوستيرويد — مضاد التهاب قوي',halfLife:'2-4 ساعة (تأثير 18-36 ساعة)',blackBox:'',notes:'لا توقف فجأة بعد >3 أسابيع. 08:00 لمحاكاة الإيقاع الطبيعي.',optimalTime:'08:00 08:00',category2:'كورتيكوستيرويد فموي'},

{id:'d075',name:'Dexamethasone (ديكساميثازون)',category:'كورتيكوستيرويدات',dose:'0.5-10mg',freq:'حسب المؤشر',timing:'08:00',food:'مع الطعام',route:'فموي / وريدي',sideEffects:'مثل Prednisolone لكن أشد',contraindications:'عدوى جهازية غير معالجة',renalAdj:'لا تعديل',interactions:'مثل Prednisolone',mechanism:'كورتيكوستيرويد قوي (لا يحتجز صوديوم)',halfLife:'3-4 ساعة (تأثير 36-54 ساعة)',blackBox:'',notes:'أقوى من Prednisolone ×7. مهم في الدماغ والقصبة ووذمة الوجه.',optimalTime:'08:00',category2:'كورتيكوستيرويد'},

{id:'d076',name:'Apixaban (أبيكسابان)',category:'القلب والأوعية / Cardiovascular',dose:'2.5-5mg',freq:'Twice daily (BID) / مرتين يومياً',timing:'08:00, 20:00',food:'Regardless of food / بغض النظر عن الطعام',route:'Oral / فموي',sideEffects:'Bleeding, anemia / نزيف، أنيميا',contraindications:'Active bleeding / نزيف نشط',renalAdj:'Adjust if CrCl < 25 / تعديل لوظائف الكلى',interactions:'Strong CYP3A4 inhibitors / مثبطات السيتوكروم',mechanism:'Factor Xa inhibitor',halfLife:'12 hours',blackBox:'Premature discontinuation increases thrombotic risk',notes:'No routine monitoring needed / لا يحتاج مراقبة دورية',optimalTime:'08:00, 20:00',category2:'Anticoagulant / مضاد تخثر'},
{id:'d077',name:'Pantoprazole IV (بانتوبرازول وريدي)',category:'الجهاز الهضمي / GI',dose:'40-80mg',freq:'Once or Twice daily / مرة أو مرتين',timing:'08:00',food:'N/A',route:'Intravenous (IV) / وريدي',sideEffects:'Headache, diarrhea / صداع، إسهال',contraindications:'Hypersensitivity / حساسية',renalAdj:'None / لا تعديل',interactions:'Reduced absorption of pH-dependent drugs / يقلل امتصاص بعض الأدوية',mechanism:'Proton Pump Inhibitor',halfLife:'1 hour',blackBox:'',notes:'Push over 2 mins / يعطى ببطء',optimalTime:'08:00',category2:'PPI'},
{id:'d078',name:'Ceftriaxone (سيفترياكسون)',category:'مضادات حيوية / Antibiotics',dose:'1-2g',freq:'Once daily (OD) / مرة يومياً',timing:'08:00',food:'N/A',route:'IV/IM / وريدي-عضلي',sideEffects:'Rash, diarrhea / طفح، إسهال',contraindications:'Neonates with hyperbilirubinemia / الخدج',renalAdj:'None / لا تعديل',interactions:'Calcium-containing IV solutions / محاليل الكالسيوم الوريدية',mechanism:'Cephalosporin 3rd gen',halfLife:'8 hours',blackBox:'',notes:'Do not mix with calcium / لا يخلط مع الكالسيوم',optimalTime:'08:00',category2:'Cephalosporin'},


// ═══════════════════════════════════════════
// Insulins (أنواع الإنسولين)
// ═══════════════════════════════════════════
{id:'d079',name:'Insulin Aspart (إنسولين أسبارت - Novorapid)',category:'السكري / Diabetes',dose:'Individualized',freq:'TID with meals / ثلاث مرات مع الوجبات',timing:'08:00, 13:00, 20:00',food:'Immediately before meals / قبل الوجبة مباشرة',route:'Subcutaneous (SC) / تحت الجلد',sideEffects:'Hypoglycemia, weight gain / نقص السكر، زيادة الوزن',contraindications:'Hypoglycemia / نقص السكر',renalAdj:'Decrease dose cautiously / تخفيض الجرعة بحذر',interactions:'Beta-blockers mask hypo / حاصرات بيتا تخفي أعراض نقص السكر',mechanism:'Rapid-acting insulin',halfLife:'1.5 hours',blackBox:'',notes:'Fast onset (10-20 min) / بداية مفعول سريعة',optimalTime:'Meals / مع الوجبات',category2:'Rapid Insulin / إنسولين سريع'},
{id:'d080',name:'Insulin Lispro (إنسولين ليسبرو - Humalog)',category:'السكري / Diabetes',dose:'Individualized',freq:'TID with meals / ثلاث مرات مع الوجبات',timing:'08:00, 13:00, 20:00',food:'Within 15 mins of meal / خلال 15 دقيقة من الوجبة',route:'Subcutaneous (SC) / تحت الجلد',sideEffects:'Hypoglycemia / نقص سكر',contraindications:'Hypoglycemia / نقص سكر',renalAdj:'Dose reduction / تخفيض الجرعة',interactions:'Steroids increase glucose / الكورتيزون يرفع السكر',mechanism:'Rapid-acting insulin',halfLife:'1 hour',blackBox:'',notes:'Do not mix with long acting in same syringe / لا يخلط مع طويل المفعول بنفس الإبرة',optimalTime:'Meals / مع الوجبات',category2:'Rapid Insulin / إنسولين سريع'},
{id:'d081',name:'Insulin NPH (إنسولين معكر NPH)',category:'السكري / Diabetes',dose:'Individualized',freq:'BID / مرتين يومياً',timing:'08:00, 20:00',food:'Maintain consistent meals / وجبات ثابتة لتجنب نقص السكر',route:'Subcutaneous (SC) / تحت الجلد',sideEffects:'Hypoglycemia, lipodystrophy / نقص سكر، تغير بالدهن تحت الجلد',contraindications:'Hypoglycemia / نقص سكر',renalAdj:'Reduce dose / تقليل الجرعة',interactions:'Alcohol increases hypo risk / الكحول يزيد خطر الهبوط',mechanism:'Intermediate-acting insulin',halfLife:'Unknown',blackBox:'',notes:'Cloudy insulin. Roll gently before use / معكر، يجب تقليبه برفق قبل الاستخدام',optimalTime:'08:00, 20:00',category2:'Intermediate Insulin / إنسولين متوسط'},
{id:'d082',name:'Insulin Degludec (إنسولين ديجلوديك - Tresiba)',category:'السكري / Diabetes',dose:'Individualized',freq:'OD / مرة يومياً',timing:'20:00',food:'Regardless of food / بغض النظر عن الطعام',route:'Subcutaneous (SC) / تحت الجلد',sideEffects:'Hypoglycemia / نقص السكر',contraindications:'Hypoglycemia / هبوط السكر',renalAdj:'Adjust cautiously / يعدل بحذر',interactions:'Pioglitazone increases heart failure risk / بيوجليتازون يزيد خطر قصور القلب',mechanism:'Ultra-long acting insulin',halfLife:'25 hours (lasts >42h)',blackBox:'',notes:'Very stable basal profile / تأثير قاعدي مستقر جداً',optimalTime:'Any fixed time / أي وقت ثابت',category2:'Ultra-long Insulin / إنسولين طويل جداً'},

// ═══════════════════════════════════════════
// Heart Meds (أدوية القلب)
// ═══════════════════════════════════════════
{id:'d083',name:'Rosuvastatin (روسوفاستاتين - Crestor)',category:'القلب والأوعية / Cardiovascular',dose:'5-40mg',freq:'OD / مرة يومياً',timing:'Any time / أي وقت',food:'Regardless of food / لا علاقة بالطعام',route:'Oral (PO) / فموي',sideEffects:'Myalgia, increased LFTs / ألم عضلات، رفع إنزيمات كبد',contraindications:'Active liver disease, pregnancy / حمل، أمراض كبد',renalAdj:'Max 10mg if CrCl <30 / حد أقصى 10مجم إذا الكلى ضعيفة',interactions:'Antacids decrease absorption / مضادات الحموضة تقلل الامتصاص',mechanism:'HMG-CoA Reductase Inhibitor',halfLife:'19 hours',blackBox:'',notes:'More potent than Atorvastatin / أقوى من أتورفاستاتين',optimalTime:'Any time / أي وقت',category2:'Statin / خافض كوليسترول'},
{id:'d084',name:'Carvedilol (كارفيديلول)',category:'القلب والأوعية / Cardiovascular',dose:'3.125-25mg',freq:'BID / مرتين يومياً',timing:'08:00, 20:00',food:'With food to slow absorption / مع الطعام لتجنب هبوط الضغط',route:'Oral (PO) / فموي',sideEffects:'Bradycardia, dizziness / بطء قلب، دوخة',contraindications:'Asthma, 2nd/3rd degree AV block / ربو، إحصار قلبي',renalAdj:'No adjustment / لا تعديل',interactions:'Digoxin (increases levels) / يرفع مستوى الديجوكسين',mechanism:'Non-selective Beta & Alpha-1 blocker',halfLife:'7-10 hours',blackBox:'Do not stop abruptly / لا يوقف فجأة',notes:'First-line in Heart Failure / أساسي في قصور القلب',optimalTime:'08:00, 20:00 with food',category2:'Beta-Blocker / حاصر بيتا'},
{id:'d085',name:'Sacubitril/Valsartan (ساكوبيتريل/فالسارتان - Entresto)',category:'القلب والأوعية / Cardiovascular',dose:'24/26mg - 97/103mg',freq:'BID / مرتين يومياً',timing:'08:00, 20:00',food:'Regardless of food / بغض النظر عن الطعام',route:'Oral (PO) / فموي',sideEffects:'Hypotension, Hyperkalemia / هبوط ضغط، ارتفاع بوتاسيوم',contraindications:'Pregnancy, Hx of angioedema / حمل، وذمة وعائية سابقة',renalAdj:'Reduce dose if CrCl <30 / تقليل الجرعة للقصور الشديد',interactions:'ACE inhibitors (washout 36h required) / يجب إيقاف الـ ACE قبلها بـ 36 ساعة',mechanism:'ARNI (Neprilysin inhibitor + ARB)',halfLife:'1-2h (Sacubitril), 10h (Valsartan)',blackBox:'Fetal toxicity / سمية جنينية',notes:'Replaces ACE/ARB in heart failure / يحل محل مثبطات ACE في قصور القلب',optimalTime:'08:00, 20:00',category2:'ARNI'},
{id:'d086',name:'Ticagrelor (تيكاجريلور - Brilinta)',category:'القلب والأوعية / Cardiovascular',dose:'90mg',freq:'BID / مرتين يومياً',timing:'08:00, 20:00',food:'Regardless of food / لا علاقة للطعام',route:'Oral (PO) / فموي',sideEffects:'Bleeding, Dyspnea (shortness of breath) / نزيف، ضيق تنفس',contraindications:'Active bleeding, Hx intracranial bleed / نزيف نشط، نزيف دماغي سابق',renalAdj:'No adjustment / لا تعديل',interactions:'Aspirin >100mg reduces efficacy / الأسبرين العالي يقلل مفعوله',mechanism:'P2Y12 platelet inhibitor',halfLife:'7-8 hours',blackBox:'Bleeding risk / خطر النزيف',notes:'Dyspnea is common and usually benign / ضيق التنفس شائع وغالباً غير خطير',optimalTime:'08:00, 20:00',category2:'Antiplatelet / مضاد صفائح'},

// ═══════════════════════════════════════════
// Eye Drops (قطرات العيون)
// ═══════════════════════════════════════════
{id:'d087',name:'Latanoprost Eye Drops (لاتانوبروست - Xalatan)',category:'العيون / Ophthalmology',dose:'1 drop / قطرة واحدة',freq:'OD / مرة يومياً',timing:'20:00-22:00 (Evening)',food:'N/A',route:'Ophthalmic / قطرة للعين',sideEffects:'Eye pigmentation, eyelash growth / تصبغ العين، نمو الرموش',contraindications:'Hypersensitivity / حساسية',renalAdj:'N/A',interactions:'None significant / لا شيء يذكر',mechanism:'Prostaglandin analog (increases outflow)',halfLife:'17 mins in blood',blackBox:'',notes:'Remove contacts before use / إزالة العدسات اللاصقة قبل التقطير',optimalTime:'Evening / مساءً (20:00)',category2:'Anti-Glaucoma / مضاد الجلوكوما'},
{id:'d088',name:'Timolol Eye Drops (تيمولول)',category:'العيون / Ophthalmology',dose:'1 drop / قطرة واحدة',freq:'BID / مرتين يومياً',timing:'08:00, 20:00',food:'N/A',route:'Ophthalmic / قطرة للعين',sideEffects:'Systemic beta-blocker effects, burning / تأثيرات قلبية وتنفسية، حرقان',contraindications:'Asthma, severe COPD, bradycardia / ربو، بطء قلب',renalAdj:'N/A',interactions:'Systemic beta-blockers (additive) / حاصرات بيتا الفموية',mechanism:'Non-selective Beta-blocker',halfLife:'N/A',blackBox:'',notes:'Pinch inner eye corner to prevent systemic absorption / اضغط على زاوية العين لمنع الامتصاص للدم',optimalTime:'08:00, 20:00',category2:'Anti-Glaucoma'},
{id:'d089',name:'Dorzolamide (دورزولاميد)',category:'العيون / Ophthalmology',dose:'1 drop / قطرة واحدة',freq:'TID / ثلاث مرات (أو مرتين)',timing:'08:00, 14:00, 20:00',food:'N/A',route:'Ophthalmic / قطرة للعين',sideEffects:'Bitter taste, burning / طعم مر، حرقان',contraindications:'Sulfa allergy (caution) / حساسية السلفا',renalAdj:'N/A',interactions:'Oral carbonic anhydrase inhibitors / مدرات البول المماثلة',mechanism:'Carbonic Anhydrase Inhibitor',halfLife:'147 days (RBC)',blackBox:'',notes:'Wait 5 mins between different eye drops / انتظر 5 دقائق بين القطرات المختلفة',optimalTime:'Spread evenly / موزعة',category2:'Anti-Glaucoma'},
{id:'d090',name:'Olopatadine (أولوباتادين - Pataday)',category:'العيون / Ophthalmology',dose:'1 drop / قطرة واحدة',freq:'OD or BID / مرة أو مرتين',timing:'Morning / صباحاً',food:'N/A',route:'Ophthalmic / قطرة للعين',sideEffects:'Eye irritation, headache / تهيج العين، صداع',contraindications:'Hypersensitivity / حساسية',renalAdj:'N/A',interactions:'None / لا يوجد',mechanism:'Mast cell stabilizer & Antihistamine',halfLife:'3 hours',blackBox:'',notes:'Do not use while wearing contacts / لا يستخدم أثناء لبس العدسات',optimalTime:'Morning / صباحاً',category2:'Anti-allergy / مضاد حساسية'},

// ═══════════════════════════════════════════
// Asthma/COPD Inhalers (بخاخات الربو والـ COPD)
// ═══════════════════════════════════════════
{id:'d091',name:'Tiotropium (تيوتروبيوم - Spiriva)',category:'الجهاز التنفسي / Respiratory',dose:'2 puffs (or 1 capsule) / بخختين أو كبسولة',freq:'OD / مرة يومياً',timing:'Morning / صباحاً',food:'N/A',route:'Inhalation / استنشاق',sideEffects:'Dry mouth, urinary retention / جفاف فم، احتباس بول',contraindications:'Hypersensitivity / حساسية',renalAdj:'Monitor in severe impairment / مراقبة في القصور الشديد',interactions:'Other anticholinergics / مضادات الكولين الأخرى',mechanism:'Long-acting Muscarinic Antagonist (LAMA)',halfLife:'5-6 days',blackBox:'',notes:'Maintenance for COPD / علاج وقائي أساسي للـ COPD',optimalTime:'Morning / صباحاً',category2:'LAMA Inhaler / بخاخ موسع'},
{id:'d092',name:'Ipratropium/Albuterol (إبراتروبيوم/ألبوتيرول - Combivent)',category:'الجهاز التنفسي / Respiratory',dose:'1 puff / بخة واحدة',freq:'QID / 4 مرات يومياً',timing:'08:00, 12:00, 16:00, 20:00',food:'N/A',route:'Inhalation / استنشاق',sideEffects:'Dry mouth, tachycardia / جفاف فم، تسرع قلب',contraindications:'Hypersensitivity to atropine/soy / حساسية للأتروبين',renalAdj:'N/A',interactions:'Anticholinergics, Beta-blockers / حاصرات بيتا',mechanism:'SAMA + SABA',halfLife:'2 hours',blackBox:'',notes:'Avoid spraying in eyes / تجنب الرش في العين',optimalTime:'Spread evenly / أوقات موزعة',category2:'SAMA/SABA Combo'},
{id:'d093',name:'Budesonide/Formoterol (بوديزونيد/فورموتيرول - Symbicort)',category:'الجهاز التنفسي / Respiratory',dose:'2 puffs / بخختين',freq:'BID / مرتين يومياً',timing:'08:00, 20:00',food:'N/A',route:'Inhalation / استنشاق',sideEffects:'Oral thrush, tremor / فطريات الفم، رجفة',contraindications:'Primary treatment of status asthmaticus / ليس للنوبات الحادة جداً',renalAdj:'N/A',interactions:'Strong CYP3A4 inhibitors / مثبطات السيتوكروم',mechanism:'ICS + LABA',halfLife:'10 hours',blackBox:'Asthma-related death risk if LABA used without ICS / خطر مترافق مع LABA',notes:'Rinse mouth after use / اغسل الفم بالماء بعد الاستخدام لمنع الفطريات',optimalTime:'08:00, 20:00',category2:'ICS/LABA Combo'},
{id:'d094',name:'Fluticasone/Salmeterol (فلوتيكازون/سالميتيرول - Seretide)',category:'الجهاز التنفسي / Respiratory',dose:'1-2 puffs / بخة-بخختين',freq:'BID / مرتين يومياً',timing:'08:00, 20:00',food:'N/A',route:'Inhalation / استنشاق',sideEffects:'Oral thrush, headache / فطريات الفم، صداع',contraindications:'Status asthmaticus / الربو الحاد',renalAdj:'N/A',interactions:'CYP3A4 inhibitors, beta-blockers / حاصرات بيتا',mechanism:'ICS + LABA',halfLife:'14 hours',blackBox:'Asthma-related death (class effect) / خطر LABA',notes:'Rinse mouth and spit after use / اغسل فمك وابصق الماء',optimalTime:'08:00, 20:00',category2:'ICS/LABA Combo'},


// ═══════════════════════════════════════════
// Additional Antibiotics (مضادات حيوية إضافية)
// ═══════════════════════════════════════════
{id:'d095',name:'Meropenem (ميروبينيم)',category:'مضادات حيوية / Antibiotics',dose:'500mg-1g',freq:'q8h / كل 8 ساعات',timing:'08:00, 16:00, 24:00',food:'N/A',route:'IV / وريدي',sideEffects:'Seizures (high doses), rash / تشنجات، طفح',contraindications:'Hypersensitivity to carbapenems / حساسية الكاربابينيم',renalAdj:'Dose reduction if CrCl <50 / تقليل الجرعة',interactions:'Valproic acid (decreases levels) / يقلل مستوى دواء الصرع',mechanism:'Carbapenem (Cell wall synthesis inhibitor)',halfLife:'1 hour',blackBox:'',notes:'Administer over 15-30 mins / يعطى ببطء',optimalTime:'08:00, 16:00, 24:00',category2:'Carbapenem'},
{id:'d096',name:'Piperacillin/Tazobactam (بيبيراسيلين/تازوباكتام - Tazocin)',category:'مضادات حيوية / Antibiotics',dose:'4.5g',freq:'q6h-q8h / كل 6-8 ساعات',timing:'06:00, 12:00, 18:00, 24:00',food:'N/A',route:'IV / وريدي',sideEffects:'Diarrhea, rash, nephrotoxicity / إسهال، سمية كلوية',contraindications:'Penicillin allergy / حساسية البنسلين',renalAdj:'Adjust if CrCl <40 / تقليل الجرعة',interactions:'Vancomycin (increased AKI risk) / يزيد سمية الكلى مع الفانكومايسين',mechanism:'Penicillin + Beta-lactamase inhibitor',halfLife:'1 hour',blackBox:'',notes:'Extended infusion (4h) improves efficacy / التسريب البطيء أفضل',optimalTime:'06:00, 12:00, 18:00, 24:00',category2:'Penicillin'},
{id:'d097',name:'Vancomycin (فانكومايسين)',category:'مضادات حيوية / Antibiotics',dose:'15-20mg/kg',freq:'q12h / كل 12 ساعة',timing:'08:00, 20:00',food:'N/A',route:'IV / وريدي',sideEffects:'Nephrotoxicity, Red Man Syndrome / سمية كلوية، متلازمة الرجل الأحمر',contraindications:'Hypersensitivity / حساسية',renalAdj:'Adjust based on trough levels / تعديل حسب مستوى الدواء بالدم',interactions:'Other nephrotoxins / الأدوية السامة للكلى',mechanism:'Glycopeptide',halfLife:'4-6 hours',blackBox:'',notes:'Infuse slowly to prevent Red Man Syndrome / التسريب ببطء شديد لمنع التحسس',optimalTime:'08:00, 20:00',category2:'Glycopeptide'},

// ═══════════════════════════════════════════
// Additional Eye Drops (قطرات عيون إضافية)
// ═══════════════════════════════════════════
{id:'d098',name:'Ciprofloxacin Eye Drops (سيبروفلوكساسين)',category:'العيون / Ophthalmology',dose:'1-2 drops',freq:'q2h to QID / كل ساعتين إلى 4 مرات',timing:'08:00, 12:00, 16:00, 20:00',food:'N/A',route:'Ophthalmic / قطرة للعين',sideEffects:'White crystalline precipitate, burning / ترسبات بيضاء، حرقان',contraindications:'Hypersensitivity / حساسية',renalAdj:'N/A',interactions:'None / لا يوجد',mechanism:'Fluoroquinolone',halfLife:'N/A',blackBox:'',notes:'Common for corneal ulcers / شائعة لقرحة القرنية',optimalTime:'Spread evenly / موزعة',category2:'Antibiotic Eye Drop'},
{id:'d099',name:'Tobramycin/Dexamethasone (توبراديكس - TobraDex)',category:'العيون / Ophthalmology',dose:'1-2 drops',freq:'QID / 4 مرات يومياً',timing:'08:00, 12:00, 16:00, 20:00',food:'N/A',route:'Ophthalmic / قطرة للعين',sideEffects:'Elevated IOP, cataracts / ارتفاع ضغط العين، الساد',contraindications:'Viral/fungal eye infections / الالتهابات الفيروسية والفطرية',renalAdj:'N/A',interactions:'None / لا يوجد',mechanism:'Antibiotic + Corticosteroid',halfLife:'N/A',blackBox:'',notes:'Shake well before use. Do not use long-term / لا تستخدم لفترات طويلة',optimalTime:'08:00, 12:00, 16:00, 20:00',category2:'Steroid/Antibiotic Eye Drop'},

// ═══════════════════════════════════════════
// Additional Asthma PRN (أدوية الربو عند اللزوم)
// ═══════════════════════════════════════════
{id:'d100',name:'Salbutamol Nebules (فنتولين رذاذ - Ventolin)',category:'الجهاز التنفسي / Respiratory',dose:'2.5-5mg',freq:'PRN / عند الحاجة',timing:'PRN / عند الحاجة',food:'N/A',route:'Inhalation / استنشاق',sideEffects:'Tremor, tachycardia, hypokalemia / رجفة، تسرع قلب، نقص بوتاسيوم',contraindications:'Hypersensitivity / حساسية',renalAdj:'N/A',interactions:'Beta blockers (antagonize) / حاصرات بيتا',mechanism:'SABA',halfLife:'3-8 hours',blackBox:'',notes:'Used via nebulizer for acute attacks / يستخدم عبر جهاز البخار للنوبات الحادة',optimalTime:'PRN / عند الحاجة',category2:'SABA Nebulizer'},

];

// ═══════════════════════════════════════════
// قائمة الأدوية المُفشِّلة (High-Alert Medications)
// ═══════════════════════════════════════════
const HIGH_ALERT_MEDICATIONS_DEFAULT = [
  {id:'ha001',drug:'Methotrexate (ميثوتريكسات)',risk:'خطر إعطاء يومي بدلاً من أسبوعي — مميت',action:'تأكيد شفهي وكتابي للمريض. ملصق تحذيري على العلبة.',severity:'critical'},
  {id:'ha002',drug:'Insulin (إنسولين)',risk:'نقص سكر حاد — خطأ في النوع أو الجرعة',action:'تأكيد نوع الإنسولين. مراقبة سكر. تعليم ذوي المريض.',severity:'critical'},
  {id:'ha003',drug:'Warfarin (وارفارين)',risk:'نزيف داخلي — تفاعلات كثيرة ونطاق ضيق',action:'مراقبة INR دورية. تثقيف عن الأطعمة والأدوية.',severity:'critical'},
  {id:'ha004',drug:'Digoxin (ديجوكسين)',risk:'سمية قلبية — نطاق علاجي ضيق',action:'مراقبة مستوى الدواء. مراقبة البوتاسيوم.',severity:'critical'},
  {id:'ha005',drug:'Lithium (ليثيوم)',risk:'سمية عصبية — نطاق ضيق وتفاعلات كثيرة',action:'مراقبة مستوى الدواء كل 3 أشهر.',severity:'critical'},
  {id:'ha006',drug:'Heparin & LMWH (هيبارين)',risk:'نزيف — جرعة غير صحيحة',action:'التحقق من الوزن والجرعة المناسبة.',severity:'critical'},
  {id:'ha007',drug:'Opioids (مورفين، فنتانيل، أوكسيكودون)',risk:'اكتئاب تنفسي ووفاة',action:'تثقيف عن علامات الجرعة الزائدة. Naloxone متاح.',severity:'critical'},
  {id:'ha008',drug:'Concentrated Electrolytes (KCl وريدي)',risk:'توقف قلب فوري لو أُعطي بسرعة',action:'يجب تخفيفه دائماً. لا يُعطى بولعة IV',severity:'critical'},
  {id:'ha009',drug:'Chemotherapy (علاجات كيماوية)',risk:'سمية متعددة — ضيق علاجي',action:'تأكيد البروتوكول والسطح الجسمي. صيدلاني متخصص.',severity:'critical'},
  {id:'ha010',drug:'Amiodarone (أميودارون)',risk:'اضطراب نظم خطير، سمية رئوية/كبدية/درقية',action:'مراقبة دورية شاملة. مراجعة التفاعلات.',severity:'high'},
  {id:'ha011',drug:'Metformin (ميتفورمين) + صبغة وريدية',risk:'حماض لبني خطير',action:'وقف Metformin 48 ساعة قبل وبعد الصبغة.',severity:'high'},
  {id:'ha012',drug:'Clopidogrel قبل جراحة',risk:'نزيف جراحي مفرط',action:'وقف 5-7 أيام قبل الجراحة إلا بتوجيه القلب.',severity:'high'},
  {id:'ha013',drug:'ACE Inhibitors + ARBs معاً',risk:'قصور كلوي حاد، فرط بوتاسيوم',action:'تجنب التركيب — مخالف للبروتوكول.',severity:'high'},
  {id:'ha014',drug:'NSAIDs + Warfarin',risk:'نزيف هضمي وزيادة INR',action:'تجنب أو مراقبة مكثفة مع PPI.',severity:'high'},
  {id:'ha015',drug:'Levothyroxine + Calcium/Iron',risk:'تقليل امتصاص الهرمون الدرقي — هشاشة التحكم',action:'فصل الجرعات بـ 4 ساعات على الأقل.',severity:'moderate'},
  {id:'ha016',drug:'Fluoroquinolones + Antacids',risk:'تقليل امتصاص المضاد الحيوي بشكل كبير',action:'فصل الجرعات بساعتين على الأقل.',severity:'moderate'},
  {id:'ha017',drug:'Simvastatin + Amiodarone/Amlodipine',risk:'رابدوميوليسيس',action:'تحديد الجرعة القصوى (20mg).',severity:'high'},
  {id:'ha018',drug:'Tramadol + SSRIs',risk:'متلازمة السيروتونين — خطر الوفاة',action:'تجنب أو مراقبة مكثفة.',severity:'critical'},
  {id:'ha019',drug:'MAOIs + أي مضاد اكتئاب',risk:'متلازمة سيروتونين، أزمة ضغطية',action:'فترة غسيل 14 يوماً على الأقل.',severity:'critical'},
  {id:'ha020',drug:'Colchicine + Clarithromycin',risk:'تراكم Colchicine — قد يكون مميتاً',action:'تجنب التركيب. استبدل المضاد الحيوي.',severity:'critical'},
];

// ═══════════════════════════════════════════
// تصدير القاعدة
// ═══════════════════════════════════════════
function getDrugDB() {
  const stored = localStorage.getItem('cp_drug_db');
  let useStored = false;
  if (stored) {
    try {
       const parsed = JSON.parse(stored);
       if (parsed.length > 95) useStored = true; // We know we have 100 drugs now
    } catch(e) {}
  }
  if (useStored) return JSON.parse(stored);
  localStorage.setItem('cp_drug_db', JSON.stringify(DRUG_DATABASE_DEFAULT));
  return DRUG_DATABASE_DEFAULT;
}

function getHighAlertDB() {
  const stored = localStorage.getItem('cp_high_alert_db');
  if (stored) return JSON.parse(stored);
  localStorage.setItem('cp_high_alert_db', JSON.stringify(HIGH_ALERT_MEDICATIONS_DEFAULT));
  return HIGH_ALERT_MEDICATIONS_DEFAULT;
}

function saveDrugDB(db) { localStorage.setItem('cp_drug_db', JSON.stringify(db)); }
function saveHighAlertDB(db) { localStorage.setItem('cp_high_alert_db', JSON.stringify(db)); }
